FROM ruby:3.1.0


RUN apt-get update -qq && apt-get install --no-install-recommends -y \
  build-essential libpq-dev && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV APP_HOME /backend

RUN echo "gem: --no-rdoc --no-ri" > /etc/gemrc

WORKDIR $APP_HOME

COPY Gemfile Gemfile.lock ./

RUN bundle check || bundle install --jobs 20 --retry 5

COPY . .

RUN chmod +x ./dev-docker-entrypoint.sh

ENTRYPOINT ["./dev-docker-entrypoint.sh"]

CMD ["rails", "s", "-p", "3000", "-b", "0.0.0.0"]
