version: '3.4'

x-backend:
  &backend
  build:
    context: .
    dockerfile: Dockerfile.dev
  environment:
    RAILS_ENV: development
    DB_USERNAME: postgres
    DB_PASSWORD: secret
    DB_HOST: db
    DB_PORT: 5432
    DB_NAME: cards_db
    SECRET_KEY_BASE: STUB
    RAILS_MAX_THREADS: 350
    SIDEKIQ_CONCURRENCY: 205
    REDIS_URL: redis://redis:6379/0
  restart: on-failure:3
  stdin_open: true
  tty: true
  volumes:
    - .:/backend:rw
    - bundle_cache:/bundle

services:
  backend:
    <<: *backend
    ports:
      - 3000:3000/tcp
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:6.2.12-alpine'
    command: redis-server
    volumes:
      - redis:/data

  sidekiq:
    <<: *backend
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - redis
      - backend

volumes:
  bundle_cache:
  postgres:
  redis:
