
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: cards_app_development

# test:
#   <<: *default
#   database: cards_app_test

# production:
#   <<: *default
#   database: cards_app_production
#   username: cards_app
#   password: <%= ENV["CARDS_APP_DATABASE_PASSWORD"] %>


default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>
  pool: <%= ENV["RAILS_MAX_THREADS"] { 5 } %>
  variables:
    statement_timeout: 5000

development:
  <<: *default
  database: <%= ENV["DB_NAME"] %>_development

test:
  <<: *default
  database: <%= ENV["DB_NAME"] %>_test

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>_production
